// apps/nuxt-app/pages/admin/blog/[id]/index.vue
<template>
  <div class="container mx-auto py-10 px-5">
    <!-- Back link -->
    <div class="flex items-center mb-6">
      <NuxtLink to="/admin/blog" class="text-primary hover:text-primary/80">
        ← {{ t('actions.backToBlog') }}
      </NuxtLink>
    </div>

    <!-- Page title -->
    <h1 class="text-3xl font-bold mb-6">
      {{ isEditMode ? t('admin.blog.editPost') : t('admin.blog.createPost') }}
    </h1>

    <!-- Error message -->
    <div v-if="errorMessage" class="mb-4 p-4 text-destructive bg-destructive/10 rounded-md">
      {{ errorMessage }}
    </div>

    <!-- Loading skeleton -->
    <div v-if="pending" class="max-w-5xl mx-auto">
      <Card>
        <CardHeader>
          <Skeleton class="h-7 w-40 mb-2" />
          <Skeleton class="h-4 w-60" />
        </CardHeader>
        <CardContent class="space-y-4">
          <div v-for="i in 6" :key="i" class="space-y-2">
            <Skeleton class="h-5 w-24" />
            <Skeleton class="h-10 w-full" />
          </div>
        </CardContent>
        <CardFooter class="pt-6">
          <Skeleton class="h-10 w-32" />
        </CardFooter>
      </Card>
    </div>

    <!-- Form -->
    <form v-else @submit="onSubmit" class="max-w-5xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>{{ t('admin.blog.form.title') }}</CardTitle>
          <CardDescription>{{ t('admin.blog.form.description') }}</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <!-- Title field -->
          <div class="space-y-2">
            <Label for="title">{{ t('admin.blog.form.labels.title') }}</Label>
            <Input
              id="title"
              v-model="title"
              :placeholder="t('admin.blog.form.placeholders.title')"
              @input="autoGenerateSlug"
            />
          </div>

          <!-- Slug field -->
          <div class="space-y-2">
            <Label for="slug">{{ t('admin.blog.form.labels.slug') }}</Label>
            <Input
              id="slug"
              v-model="slug"
              :placeholder="t('admin.blog.form.placeholders.slug')"
            />
          </div>

          <!-- Excerpt field -->
          <div class="space-y-2">
            <Label for="excerpt">{{ t('admin.blog.form.labels.excerpt') }}</Label>
            <textarea
              id="excerpt"
              v-model="excerpt"
              :placeholder="t('admin.blog.form.placeholders.excerpt')"
              class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              rows="3"
            />
          </div>

          <!-- Cover image field -->
          <div class="space-y-2">
            <Label for="coverImage">{{ t('admin.blog.form.labels.coverImage') }}</Label>
            <!-- Show current cover image preview if exists -->
            <div v-if="coverImage" class="relative mb-2">
              <img
                :src="coverImage"
                alt="Cover"
                class="w-full h-48 object-cover rounded-md border"
              />
              <Button
                type="button"
                variant="destructive"
                size="sm"
                class="absolute top-2 right-2"
                @click="coverImage = ''"
              >
                {{ t('actions.delete') }}
              </Button>
            </div>
            <FileUpload
              v-if="!coverImage"
              :model-value="[]"
              accept="image/*"
              :max-files="1"
              :max-size="2 * 1024 * 1024"
              :on-upload="uploadCoverImage"
            >
              <FileUploadDropzone class="border-dashed p-6">
                <div class="flex flex-col items-center gap-2 text-center">
                  <Upload class="h-8 w-8 text-muted-foreground" />
                  <p class="text-sm text-muted-foreground">
                    {{ t('admin.blog.form.placeholders.coverImage') }}
                  </p>
                </div>
              </FileUploadDropzone>
            </FileUpload>
          </div>

          <!-- Status field -->
          <div class="space-y-2">
            <Label for="status">{{ t('admin.blog.form.labels.status') }}</Label>
            <Select v-model="status">
              <SelectTrigger>
                <SelectValue :placeholder="t('admin.blog.form.labels.status')" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="draft">{{ t('admin.blog.table.search.draft') }}</SelectItem>
                <SelectItem value="published">{{ t('admin.blog.table.search.published') }}</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <!-- Content field (Markdown editor) -->
          <div class="space-y-2">
            <Label for="content">{{ t('admin.blog.form.labels.content') }}</Label>
            <ClientOnly>
              <MdEditor v-model="content" language="en-US" class="min-h-[400px]" :on-upload-img="handleEditorUploadImg" />
              <template #fallback>
                <div class="min-h-[400px] rounded-md border border-input bg-muted/50 flex items-center justify-center text-muted-foreground">
                  {{ t('common.loading') }}
                </div>
              </template>
            </ClientOnly>
          </div>
        </CardContent>
        <CardFooter class="flex justify-between space-x-4 pt-6">
          <div class="flex space-x-4">
            <Button type="submit" :disabled="isSubmitting" class="flex items-center gap-2">
              <Save class="h-4 w-4" />
              {{ isSubmitting ? t('common.loading') : t('actions.saveChanges') }}
            </Button>

            <!-- Delete button (only for edit mode) -->
            <AlertDialog v-if="isEditMode">
              <AlertDialogTrigger as-child>
                <Button variant="destructive" type="button" class="flex items-center gap-2">
                  <Trash2 class="h-4 w-4" />
                  {{ t('actions.deletePost') }}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>{{ t('admin.blog.deleteDialog.title') }}</AlertDialogTitle>
                  <AlertDialogDescription>
                    {{ t('admin.blog.deleteDialog.description') }}
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>{{ t('actions.cancel') }}</AlertDialogCancel>
                  <AlertDialogAction
                    @click="handleDelete"
                    class="bg-destructive hover:bg-destructive/90"
                  >
                    {{ t('actions.delete') }}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </CardFooter>
      </Card>
    </form>
  </div>
</template>

<script setup lang="ts">
import { MdEditor } from 'md-editor-v3'
import 'md-editor-v3/lib/style.css'
import { Save, Trash2, Upload } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { createBlogPostValidators } from '@libs/validators'

definePageMeta({
  layout: 'admin',
})

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const localePath = useLocalePath()

const { blogPostFormSchema } = createBlogPostValidators(t)

const postId = route.params.id as string
const isEditMode = postId !== 'new'

const title = ref('')
const slug = ref('')
const excerpt = ref('')
const coverImage = ref('')
const status = ref<'draft' | 'published'>('draft')
const content = ref('')

const pending = ref(false)
const isSubmitting = ref(false)
const errorMessage = ref('')

/** Generate URL-friendly slug from title */
function generateSlugFromTitle(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'post'
}

const autoGenerateSlug = () => {
  if (title.value.trim()) {
    slug.value = generateSlugFromTitle(title.value)
  }
}

/** Upload cover image via storage API; adapts to FileUpload onUpload signature */
const uploadCoverImage = async (
  files: File[],
  options: {
    onProgress: (file: File, progress: number) => void
    onSuccess: (file: File) => void
    onError: (file: File, error: Error) => void
  }
) => {
  const file = files[0]
  if (!file) return
  const formData = new FormData()
  formData.append('file', file)
  formData.append('provider', 'r2')
  try {
    const res = await $fetch<{ data: { url: string } }>('/api/upload', {
      method: 'POST',
      body: formData,
    })
    coverImage.value = res.data?.url || ''
    toast.success(t('admin.blog.messages.uploadSuccess'))
    options.onSuccess(file)
  } catch (err) {
    toast.error(t('admin.blog.messages.uploadError'))
    options.onError(file, err instanceof Error ? err : new Error(String(err)))
  }
}

/** Handle image upload from markdown editor (paste/drag) */
const handleEditorUploadImg = async (files: File[], callback: (urls: string[]) => void) => {
  const urls: string[] = []
  for (const file of files) {
    const formData = new FormData()
    formData.append('file', file)
    formData.append('provider', 'r2')
    try {
      const res = await $fetch<{ data: { url: string } }>('/api/upload', {
        method: 'POST',
        body: formData,
      })
      if (res.data?.url) {
        urls.push(res.data.url)
      }
    } catch {
      toast.error(t('admin.blog.messages.uploadError'))
    }
  }
  callback(urls)
}

// Fetch post data for edit mode
if (isEditMode) {
  const { data } = await useFetch(`/api/admin/blog/${postId}`, {
    server: false,
    onRequest() {
      pending.value = true
    },
    onResponse({ response }) {
      pending.value = false
      const row = response._data
      if (row) {
        title.value = row.title || ''
        slug.value = row.slug || ''
        excerpt.value = row.excerpt || ''
        coverImage.value = row.coverImage || ''
        status.value = (row.status as 'draft' | 'published') || 'draft'
        content.value = row.content || ''
      }
    },
    onResponseError() {
      pending.value = false
      errorMessage.value = t('admin.blog.messages.fetchError')
    },
  })
}

const onSubmit = async (e: Event) => {
  e.preventDefault()
  isSubmitting.value = true
  errorMessage.value = ''

  const body = {
    title: title.value.trim(),
    slug: slug.value.trim() || generateSlugFromTitle(title.value),
    excerpt: excerpt.value.trim() || undefined,
    coverImage: coverImage.value.trim() || undefined,
    status: status.value,
    content: content.value,
  }

  const parseResult = blogPostFormSchema.safeParse(body)
  if (!parseResult.success) {
    const firstError = parseResult.error.issues?.[0]?.message || t('admin.blog.messages.operationFailed')
    errorMessage.value = firstError
    toast.error(firstError)
    isSubmitting.value = false
    return
  }

  try {
    if (isEditMode) {
      await $fetch(`/api/admin/blog/${postId}`, {
        method: 'PATCH',
        body,
      })
      toast.success(t('admin.blog.messages.updateSuccess'))
    } else {
      await $fetch('/api/admin/blog', {
        method: 'POST',
        body,
      })
      toast.success(t('admin.blog.messages.createSuccess'))
    }

    await router.push(localePath('/admin/blog'))
  } catch (error: any) {
    const message = error?.data?.message || t('admin.blog.messages.operationFailed')
    errorMessage.value = message
    toast.error(message)
  } finally {
    isSubmitting.value = false
  }
}

const handleDelete = async () => {
  try {
    await $fetch(`/api/admin/blog/${postId}`, { method: 'DELETE' })
    toast.success(t('admin.blog.messages.deleteSuccess'))
    await router.push(localePath('/admin/blog'))
  } catch (error: any) {
    const message = error?.data?.message || t('admin.blog.messages.deleteError')
    errorMessage.value = message
    toast.error(message)
  }
}

useHead({
  title: computed(() =>
    isEditMode ? t('admin.blog.editPost') : t('admin.blog.createPost'),
  ),
})
</script>

// apps/next-app/app/[lang]/admin/blog/[id]/page.tsx
"use client"

import { use } from "react"
import { useEffect, useState, useRef, useCallback } from "react"
import { notFound, useRouter } from "next/navigation"
import dynamic from "next/dynamic"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Label } from "@/components/ui/label"
import {
  FileUpload,
  FileUploadDropzone,
  FileUploadItem,
  FileUploadItemDelete,
  FileUploadItemMetadata,
  FileUploadItemPreview,
  FileUploadItemProgress,
  FileUploadList,
} from "@/components/ui/file-upload"
import Link from "next/link"
import { SaveIcon, Trash2Icon, Upload, X } from "lucide-react"
import { useForm, Controller } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { z } from "zod"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import { toast } from "sonner"
import { Skeleton } from "@/components/ui/skeleton"
import { useTranslation } from "@/hooks/use-translation"
import { useTheme } from "@/hooks/use-theme"
import { createBlogPostValidators, createNextTranslationFunction } from "@libs/validators"

import "@uiw/react-md-editor/markdown-editor.css"
import "@uiw/react-markdown-preview/markdown.css"

const MDEditor = dynamic(() => import("@uiw/react-md-editor"), { ssr: false })

function slugFromTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "") || "post"
}

async function uploadFile(file: File): Promise<string | null> {
  const formData = new FormData()
  formData.append("file", file)
  formData.append("provider", "r2")
  try {
    const res = await fetch("/api/upload", { method: "POST", body: formData })
    if (!res.ok) return null
    const data = await res.json()
    return data.data?.url || null
  } catch {
    return null
  }
}

interface BlogPageProps {
  params: Promise<{
    lang: string
    id?: string
  }>
}

export default function BlogPostPage({ params }: BlogPageProps) {
  const { t } = useTranslation()
  const tWithParams = createNextTranslationFunction(t)
  const { blogPostFormSchema } = createBlogPostValidators(tWithParams)
  type BlogFormData = z.infer<typeof blogPostFormSchema>

  const { theme } = useTheme()
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [coverImage, setCoverImage] = useState<string>("")
  const [coverFiles, setCoverFiles] = useState<File[]>([])
  const slugAutoGeneratedRef = useRef(true)

  const resolvedParams = use(params)
  const { id, lang } = resolvedParams
  const isEditMode = id !== "new"

  const {
    register,
    handleSubmit,
    control,
    reset,
    watch,
    setValue,
    formState: { errors },
  } = useForm<BlogFormData>({
    resolver: zodResolver(blogPostFormSchema),
    defaultValues: {
      title: "",
      slug: "",
      excerpt: "",
      coverImage: "",
      status: "draft" as const,
      content: "",
    },
    mode: "onBlur",
  })

  const title = watch("title")
  const slug = watch("slug")

  useEffect(() => {
    if (!title) return
    const newSlug = slugFromTitle(title)
    if (slugAutoGeneratedRef.current || !slug || slug.trim() === "") {
      setValue("slug", newSlug)
      slugAutoGeneratedRef.current = true
    }
  }, [title, setValue])

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    slugAutoGeneratedRef.current = false
    setValue("slug", e.target.value)
  }

  useEffect(() => {
    const fetchPost = async () => {
      if (id === "new") {
        slugAutoGeneratedRef.current = true
        setLoading(false)
        return
      }

      if (!id) {
        notFound()
      }

      try {
        const response = await fetch(`/api/admin/blog/${id}`)
        if (!response.ok) {
          throw new Error(t.admin.blog.messages.fetchError)
        }
        const post = await response.json()
        reset({
          title: post.title,
          slug: post.slug,
          excerpt: post.excerpt || "",
          coverImage: post.coverImage || "",
          status: post.status,
          content: post.content || "",
        })
        setCoverImage(post.coverImage || "")
        slugAutoGeneratedRef.current = false
        setLoading(false)
      } catch (err) {
        setError(err instanceof Error ? err.message : t.admin.blog.messages.fetchError)
        notFound()
      }
    }

    fetchPost()
  }, [id, reset, t])

  const handleCoverUpload = useCallback(
    async (
      files: File[],
      { onProgress, onSuccess, onError }: {
        onProgress: (file: File, progress: number) => void
        onSuccess: (file: File) => void
        onError: (file: File, error: Error) => void
      },
    ) => {
      const file = files[0]
      if (!file) return
      const url = await uploadFile(file)
      if (url) {
        setCoverImage(url)
        setValue("coverImage", url)
        toast.success(t.admin.blog.messages.uploadSuccess)
        onSuccess(file)
      } else {
        toast.error(t.admin.blog.messages.uploadError)
        onError(file, new Error("Upload failed"))
      }
    },
    [setValue, t],
  )

  const removeCoverImage = () => {
    setCoverImage("")
    setCoverFiles([])
    setValue("coverImage", "")
  }

  const handleEditorPaste = useCallback(
    async (e: React.ClipboardEvent) => {
      const items = e.clipboardData?.items
      if (!items) return
      for (const item of Array.from(items)) {
        if (item.type.startsWith("image/")) {
          e.preventDefault()
          const file = item.getAsFile()
          if (!file) continue
          const url = await uploadFile(file)
          if (url) {
            const currentContent = watch("content") || ""
            setValue("content", currentContent + `\n![image](${url})\n`)
            toast.success(t.admin.blog.messages.uploadSuccess)
          } else {
            toast.error(t.admin.blog.messages.uploadError)
          }
          break
        }
      }
    },
    [watch, setValue, t],
  )

  const handleEditorDrop = useCallback(
    async (e: React.DragEvent) => {
      const files = e.dataTransfer?.files
      if (!files?.length) return
      for (const file of Array.from(files)) {
        if (file.type.startsWith("image/")) {
          e.preventDefault()
          const url = await uploadFile(file)
          if (url) {
            const currentContent = watch("content") || ""
            setValue("content", currentContent + `\n![image](${url})\n`)
            toast.success(t.admin.blog.messages.uploadSuccess)
          } else {
            toast.error(t.admin.blog.messages.uploadError)
          }
        }
      }
    },
    [watch, setValue, t],
  )

  const onSubmit = async (data: BlogFormData) => {
    setError(null)

    const payload = { ...data, coverImage }
    if (!payload.slug?.trim() && payload.title) {
      payload.slug = slugFromTitle(payload.title)
    }

    try {
      if (isEditMode && id) {
        const res = await fetch(`/api/admin/blog/${id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        })
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}))
          throw new Error(errData.error || t.admin.blog.messages.operationFailed)
        }
        toast.success(t.admin.blog.messages.updateSuccess)
      } else {
        const res = await fetch("/api/admin/blog", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        })
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}))
          throw new Error(errData.error || t.admin.blog.messages.operationFailed)
        }
        toast.success(t.admin.blog.messages.createSuccess)
      }

      router.push(`/${lang}/admin/blog`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : t.admin.blog.messages.operationFailed
      setError(msg)
      toast.error(msg)
    }
  }

  const handleDelete = async () => {
    if (!id) return
    try {
      const res = await fetch(`/api/admin/blog/${id}`, { method: "DELETE" })
      if (!res.ok) {
        throw new Error(t.admin.blog.messages.deleteError)
      }
      toast.success(t.admin.blog.messages.deleteSuccess)
      router.push(`/${lang}/admin/blog`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : t.admin.blog.messages.deleteError
      setError(msg)
      toast.error(msg)
    }
  }

  if (loading) {
    return (
      <div className="container mx-auto p-10">
        <div className="mb-6">
          <Skeleton className="h-6 w-32" />
        </div>
        <Skeleton className="h-10 w-60 mb-6" />
        <Card className="max-w-5xl mx-auto">
          <CardHeader>
            <Skeleton className="h-7 w-40 mb-2" />
            <Skeleton className="h-4 w-60" />
          </CardHeader>
          <CardContent className="space-y-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="space-y-2">
                <Skeleton className="h-5 w-24" />
                <Skeleton className="h-10 w-full" />
              </div>
            ))}
          </CardContent>
          <CardFooter className="pt-6">
            <Skeleton className="h-10 w-32" />
          </CardFooter>
        </Card>
      </div>
    )
  }

  return (
    <div className="container mx-auto p-10">
      <div className="flex items-center mb-6">
        <Link href={`/${lang}/admin/blog`} className="text-blue-500 hover:text-blue-700">
          ← {t.actions.backToBlog}
        </Link>
      </div>

      <h1 className="text-3xl font-bold mb-6">
        {isEditMode ? t.admin.blog.editPost : t.admin.blog.createPost}
      </h1>

      {error && (
        <div className="mb-4 p-4 text-red-700 bg-red-100 rounded-md">{error}</div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="max-w-5xl mx-auto">
        <Card>
          <CardHeader>
            <CardTitle>{t.admin.blog.form.title}</CardTitle>
            <CardDescription>{t.admin.blog.form.description}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="title">{t.admin.blog.form.labels.title}</Label>
              <Input
                id="title"
                {...register("title")}
                placeholder={t.admin.blog.form.placeholders.title}
                className={errors.title ? "border-red-500" : ""}
              />
              {errors.title && (
                <p className="text-red-500 text-sm">{errors.title.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug">{t.admin.blog.form.labels.slug}</Label>
              <Input
                id="slug"
                value={slug}
                onChange={handleSlugChange}
                placeholder={t.admin.blog.form.placeholders.slug}
                className={errors.slug ? "border-red-500" : ""}
              />
              {errors.slug && (
                <p className="text-red-500 text-sm">{errors.slug.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="excerpt">{t.admin.blog.form.labels.excerpt}</Label>
              <textarea
                id="excerpt"
                {...register("excerpt")}
                placeholder={t.admin.blog.form.placeholders.excerpt}
                rows={3}
                className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>

            {/* Cover image upload */}
            <div className="space-y-2">
              <Label>{t.admin.blog.form.labels.coverImage}</Label>
              {coverImage ? (
                <div className="relative mb-2">
                  <img
                    src={coverImage}
                    alt="Cover"
                    className="w-full h-48 object-cover rounded-md border"
                  />
                  <Button
                    type="button"
                    variant="destructive"
                    size="sm"
                    className="absolute top-2 right-2"
                    onClick={removeCoverImage}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ) : (
                <FileUpload
                  value={coverFiles}
                  onValueChange={setCoverFiles}
                  accept="image/*"
                  maxFiles={1}
                  maxSize={2 * 1024 * 1024}
                  onUpload={handleCoverUpload}
                >
                  <FileUploadDropzone className="border-dashed p-6">
                    <div className="flex flex-col items-center gap-2 text-center">
                      <Upload className="h-8 w-8 text-muted-foreground" />
                      <p className="text-sm text-muted-foreground">
                        {t.admin.blog.form.placeholders.coverImage}
                      </p>
                    </div>
                  </FileUploadDropzone>
                  <FileUploadList>
                    {coverFiles.map((file, index) => (
                      <FileUploadItem key={index} value={file}>
                        <FileUploadItemPreview />
                        <FileUploadItemMetadata />
                        <FileUploadItemProgress />
                        <FileUploadItemDelete />
                      </FileUploadItem>
                    ))}
                  </FileUploadList>
                </FileUpload>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="status">{t.admin.blog.form.labels.status}</Label>
              <Controller
                name="status"
                control={control}
                render={({ field }) => (
                  <Select onValueChange={field.onChange} value={field.value}>
                    <SelectTrigger className={errors.status ? "border-red-500" : ""}>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="draft">
                        {t.admin.blog.table.search.draft}
                      </SelectItem>
                      <SelectItem value="published">
                        {t.admin.blog.table.search.published}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.status && (
                <p className="text-red-500 text-sm">{errors.status.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="content">{t.admin.blog.form.labels.content}</Label>
              <Controller
                name="content"
                control={control}
                render={({ field }) => (
                  <div
                    data-color-mode={theme === "dark" ? "dark" : "light"}
                    className="[&_.w-md-editor]:min-h-[300px]"
                    onPaste={handleEditorPaste}
                    onDrop={handleEditorDrop}
                    onDragOver={(e) => e.preventDefault()}
                  >
                    <MDEditor
                      value={field.value || ""}
                      onChange={field.onChange}
                      preview="live"
                      height={400}
                      visibleDragbar={false}
                    />
                  </div>
                )}
              />
            </div>
          </CardContent>
          <CardFooter className="flex justify-between space-x-4 pt-6">
            <div className="flex space-x-4">
              <Button type="submit" className="flex items-center gap-2">
                <SaveIcon className="h-4 w-4" />
                {isEditMode ? t.actions.saveChanges : t.actions.createPost}
              </Button>

              {isEditMode && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="destructive"
                      type="button"
                      className="flex items-center gap-2"
                    >
                      <Trash2Icon className="h-4 w-4" />
                      {t.actions.deletePost}
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>
                        {t.admin.blog.deleteDialog.title}
                      </AlertDialogTitle>
                      <AlertDialogDescription>
                        {t.admin.blog.deleteDialog.description}
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>{t.actions.cancel}</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={handleDelete}
                        className="bg-red-600 hover:bg-red-700"
                      >
                        {t.actions.delete}
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
            </div>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}
