// apps/next-app/app/[lang]/(root)/blog/[slug]/page.tsx
import Link from "next/link";

import { notFound } from "next/navigation";
import { db, blogPost, user } from "@libs/database";
import { blogPostStatus } from "@libs/database/schema/blog-post";
import { eq, and } from "drizzle-orm";
import { translations } from "@libs/i18n";
import type { Metadata } from "next";
import ReactMarkdown from "react-markdown";
import { ChevronLeft } from "lucide-react";

type Props = {
  params: Promise<{ lang: string; slug: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang, slug } = await params;
  const t = translations[lang as keyof typeof translations];

  const [post] = await db
    .select({
      title: blogPost.title,
      excerpt: blogPost.excerpt,
    })
    .from(blogPost)
    .where(and(eq(blogPost.slug, slug), eq(blogPost.status, blogPostStatus.PUBLISHED)))
    .limit(1);

  if (!post) {
    return {
      title: t.blog.title,
    };
  }

  return {
    title: `${post.title} - ${t.blog.title}`,
    description: post.excerpt || t.blog.metadata.description,
    keywords: t.blog.metadata.keywords,
  };
}

export default async function BlogDetailPage({ params }: Props) {
  const { lang, slug } = await params;
  const t = translations[lang as keyof typeof translations];

  const [post] = await db
    .select({
      id: blogPost.id,
      title: blogPost.title,
      slug: blogPost.slug,
      content: blogPost.content,
      excerpt: blogPost.excerpt,
      coverImage: blogPost.coverImage,
      publishedAt: blogPost.publishedAt,
      authorName: user.name,
    })
    .from(blogPost)
    .leftJoin(user, eq(blogPost.authorId, user.id))
    .where(and(eq(blogPost.slug, slug), eq(blogPost.status, blogPostStatus.PUBLISHED)))
    .limit(1);

  if (!post) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-background">
      <article className="mx-auto max-w-3xl px-6 py-16 lg:px-8">
        <Link
          href={`/${lang}/blog`}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors"
        >
          <ChevronLeft className="h-4 w-4" />
          {t.blog.backToBlog}
        </Link>

        <header className="mb-8">
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
            {post.title}
          </h1>
          <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
            {post.authorName && (
              <span>
                {t.blog.by} {post.authorName}
              </span>
            )}
            {post.publishedAt && (
              <span>
                {t.blog.publishedOn}{" "}
                {new Date(post.publishedAt).toLocaleDateString(lang === "zh-CN" ? "zh-CN" : "en-US")}
              </span>
            )}
          </div>
          {post.coverImage && (
            <div className="mt-6 aspect-video w-full overflow-hidden rounded-lg bg-muted">
              <img
                src={post.coverImage}
                alt={post.title}
                className="h-full w-full object-cover"
              />
            </div>
          )}
        </header>

        <div className="prose dark:prose-invert max-w-none">
          <ReactMarkdown>{post.content}</ReactMarkdown>
        </div>

        <footer className="mt-12 pt-8 border-t border-border">
          <Link
            href={`/${lang}/blog`}
            className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
            {t.blog.backToBlog}
          </Link>
        </footer>
      </article>
    </div>
  );
}

// apps/nuxt-app/pages/blog/[slug].vue
<template>
  <div class="min-h-screen bg-background">
    <article v-if="post" class="mx-auto max-w-3xl px-6 py-16 lg:px-8">
      <NuxtLink
        :to="localePath('/blog')"
        class="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors"
      >
        <ChevronLeft class="h-4 w-4" />
        {{ t('blog.backToBlog') }}
      </NuxtLink>

      <header class="mb-8">
        <h1 class="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
          {{ post.title }}
        </h1>
        <div class="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
          <span v-if="post.authorName">
            {{ t('blog.by') }} {{ post.authorName }}
          </span>
          <span v-if="post.publishedAt">
            {{ t('blog.publishedOn') }}
            {{ formatDate(post.publishedAt) }}
          </span>
        </div>
        <div v-if="post.coverImage" class="relative mt-6 aspect-video w-full overflow-hidden rounded-lg bg-muted">
          <img
            :src="post.coverImage"
            :alt="post.title"
            class="h-full w-full object-cover"
          />
        </div>
      </header>

      <article class="prose dark:prose-invert max-w-none">
        <VueMarkdown :source="post?.content ?? ''" />
      </article>

      <footer class="mt-12 pt-8 border-t border-border">
        <NuxtLink
          :to="localePath('/blog')"
          class="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ChevronLeft class="h-4 w-4" />
          {{ t('blog.backToBlog') }}
        </NuxtLink>
      </footer>
    </article>
  </div>
</template>

<script setup lang="ts">
import { ChevronLeft } from 'lucide-vue-next'
import VueMarkdown from 'vue-markdown-render'

const route = useRoute()
const { t, locale } = useI18n()
const localePath = useLocalePath()

const slug = computed(() => route.params.slug as string)

const { data: post, error } = await useFetch<{
  id: string
  title: string
  slug: string
  content: string
  excerpt: string | null
  coverImage: string | null
  publishedAt: string | null
  authorName: string | null
}>(() => `/api/blog/${slug.value}`, {
  key: `blog-${slug.value}`,
})

if (error.value || !post.value) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Blog post not found',
  })
}

const formatDate = (dateStr: string | null) => {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleDateString(locale.value === 'zh-CN' ? 'zh-CN' : 'en-US')
}

useSeoMeta({
  title: () => `${post.value!.title} - ${t('blog.title')}`,
  description: () => post.value!.excerpt || t('blog.metadata.description'),
  keywords: () => t('blog.metadata.keywords'),
})
</script>
